name: PR Review

on:
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Check Frontmatter
        run: pnpm check:frontmatter

      - name: Run Biome Check
        uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

      - name: Run type check
        run: pnpm typecheck

      - name: Run tests
        run: pnpm test

  # links:
  #   name: Check Links
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Check Links
  #       uses: lycheeverse/lychee-action@v2.2.0
  #       with:
  #         args: --config ./lychee.toml --verbose --no-progress .
  #         fail: true

