name: Deploy PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/actions/install

      - name: Build
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Deploy to Surge
        id: deploy
        run: |
          npm install -g surge
          export DEPLOY_DOMAIN=https://boxingundefeated-pr-${{ github.event.pull_request.number }}.surge.sh
          surge ./apps/web/out $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
          echo "url=$DEPLOY_DOMAIN" >> $GITHUB_OUTPUT

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const url = '${{ steps.deploy.outputs.url }}';
            const body = `🚀 Preview deployment ready!\n\n🔗 **Preview URL:** ${url}\n\n_This preview will be updated on every commit to this PR._`;
            
            // Find existing comment
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            
            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && comment.body.includes('Preview deployment ready')
            );
            
            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }